name: 'Release'

on:
  push:
    tags:
      - 'v*' # Trigger build when pushing tags matching v* (e.g., v0.1.1)

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest] # Only building for Windows since this is the USER's primary OS and they run NSIS installers

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend dependencies
        run: npm ci

      - name: Build and Publish Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__ # Automatically uses version defined in tauri.conf.json
          releaseName: 'Absolute Cinema v__VERSION__'
          releaseBody: 'Release generated automatically by GitHub Actions.'
          releaseDraft: true
          prerelease: false
